### PR TITLE
Don't rewrite default DEPLOY_ENVIRONMENT from config

### PR DESCRIPTION
**Pull request by belousovAV**
Don't rewrite default DEPLOY_ENVIRONMENT from config

### CODE REVIEW

**Comment by bharendt** [comment]
`staging` should always be the default environment, even if someone omits the environment in a command. If you want to be able to override the `DEPLOY_ENVIRONMENT` variable in the config, something which keeps the default would be better, e.g. ` [[ $ARGS =~ "production" ]] && export DEPLOY_ENVIRONMENT="production" || export DEPLOY_ENVIRONMENT="${DEPLOY_ENVIRONMENT:-staging}"`

**Comment by belousovAV** [comment]
But now i can't call staging from args and should remove default_env from config?

**Comment by bharendt** [comment]
This could be achieved while also preserving the default staging env with something like that:
```
if [[ -z "$DEPLOY_ENVIRONMENT" ]]; then
  [[ $ARGS =~ "production" ]] && export DEPLOY_ENVIRONMENT="production" || export DEPLOY_ENVIRONMENT="staging"
fi
```

**Comment by belousovAV** [comment]
What about this? 
First we check `args`, second - `config`, last - set default `staging`

**Comment by syamilmj** [comment]
@lessless is this something you could consider updating? Both erlang-update & erlang-upgrade has this line of code that overrides the `DEPLOY_ENVIRONMENT`

```
[[ $ARGS =~ "production" ]] && export DEPLOY_ENVIRONMENT="production" || export DEPLOY_ENVIRONMENT="staging"
```

**Comment by syamilmj** [comment]
@lessless I'll try to explain here. 

In order to support custom environment, e.g. `staging2`, we are adding `.deliver/help` where the content goes like this:

```
#!/usr/bin/env bash
accepts_custom_command_argument() {
  local _command="$1"
  local _argument="$2"
  
  case "${_command}" in
    (deploy|update|build|migrate|migrations|start|restart|stop)
      case "${_argument}" in
        (staging|staging2|production)
          DEPLOY_ENVIRONMENT="${_argument}"
          return 0 ;;
        ("") return 0 ;; # default: 'staging'
        (*)  return 1 ;; # unknown deploy environment
      esac ;;
    (*) return 1 ;; # unknown custom command
  esac
}
```

This will set `DEPLOY_ENVIRONMENT` to `staging2`.

We use this variable in a few places in the config inside deploy hooks, such as `pre_erlang_get_and_update_deps`, for example to set the config file:

```
pre_erlang_get_and_update_deps() {
  local _stag2_secret_path="$BUILD_ROOT/config/stag2.secret.exs"
  
  if [ "$DEPLOY_ENVIRONMENT" = "staging2" ]; then
      __sync_remote "
        ln -sfn '$_stag2_secret_path' '$BUILD_AT/config/prod.secret.exs'
      "
  fi
}
```

Since both erlang-update & erlang-upgrade overrides `DEPLOY_ENVIRONMENT` to `staging`, running commands such as `mix edeliver update staging2` will not set correct config file as defined above.

Hope that clarifies.

**Comment by lessless** [comment]
Thanks @syamilmj, it makes sense now. I'll look into this ASAP. Can you please weight in the https://elixirforum.com/t/thoughts-about-edeliver-2-0/19328 if you will have time?

**Comment by lessless** [comment]
@syamilmj should `erlang-update` also be updated?

**Comment by syamilmj** [comment]
@lessless Yep, they both need to be updated.

**Comment by lessless** [comment]
@syamilmj right. I'll happily merge this PR if the behaviour will be consistent across different scenarios. Maybe you or @belousovAV would like to give it another go?

**Comment by bharendt** [comment]
@belousovAV finally getting around to this (years later). Thank you!

**Pull request merged**
