### PR TITLE
POSIX compatibility

### LINKED ISSUE #143: POSIX compatibility for scripts on deploy host
... and warn or abort if bash is not the default shell on the build host. See #124.

### PR DESCRIPTION
**Pull request by bharendt**
Make all shell scripts on deploy hosts POSIX compatible. This allows to use there any shell as default shell (instead of requiring bash or zsh). Closes #143.

### CODE REVIEW

**Comment by lattenwald** [comment]
Thought I'd fix it in my fork, then create a pull-request, and looky there, there it is already waiting 8 months.

I wish this was already merged when I was fighting with `dash` being default shell in Ubuntu.

**Comment by mk** [comment]
@lattenwald sorry about that, I'll merge this now and we'll see to cut a new release soon.

**Comment by syamilmj** [comment]
This is causing an issue as reported in https://github.com/edeliver/edeliver/issues/263

Specifically this line: https://github.com/edeliver/edeliver/blob/master/libexec/erlang#L312

**Comment by nulian** [comment]
Yeah and #264 problem is mostly caused by `\"\$HOME/.profile\"` which I think needs to be `\"$HOME/.profile\"`

**Comment by nulian** [comment]
This is also the cause for #264

**Comment by lessless** [comment]
@nulian can you submit a patch please?

**Comment by nulian** [comment]
I just reverted it for me to make it work. I'm not sure what is truly valid in POSIX because of not having a lot of knowledge about that. Found out this mostly with trial and error.

**Comment by lessless** [comment]
@nulian @syamilmj I just reverted 96d64a8b19aa53b48d0fbd769aaa5c12eb0da2ef and it should fix both #263 and #264 
Can you please try a fresh master?

**Comment by nulian** [comment]
It works correctly from master now.

**Comment by syamilmj** [comment]
@lessless master doesn't work for s3 release store. Still similar issue in #263 

I tried changing this [line](https://github.com/edeliver/edeliver/blob/master/libexec/erlang#L312) to:

```
SILENCE="&> /dev/null"
```

And then it works.

Removal of `&` was introduced in ec1129b16e81de137a842b10953afd76a830dc76

**Pull request merged**
