### PR TITLE
Fix those annoying warnings in elixir 1.5

### PR DESCRIPTION
**Pull request by johannesE**
char_list => charlist and a few more

### CODE REVIEW

**Comment by lessless** [comment]
@bharendt I think this one is a good to go. Will totally help to get rid of the noise in the console.

**Comment by mk** [comment]
Thanks, I'll go ahead and merge this. @bharendt and I don't have much time maintaining edeliver anymore. Would you be interested in getting push access @lessless and or @johannesE?

**Comment by lessless** [comment]
@mk definitely! We are using it in production and I promise to try to not break anything :)

**Comment by johannesE** [comment]
> @mk definitely! We are using it in production and I promise to try to not break anything :)

Same here. I cannot guarantee lots of time, but I'll do my best.

**Comment by mk** [comment]
@lessless @johannesE great, sent out an invite for both of you. Do you have an account on hex.pm so I can grant you access there as well? You can send me your account email to github@ my last name .net. Thanks a lot for your help! 🙏

**Pull request merged**
