### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Tidy up documentation generation for Hexdocs.pm which leverages on
latest features of ExDoc.

### CODE REVIEW

**Review by lessless — APPROVED** [review]
Thank you ❤️

**Comment by lessless** [comment]
@kianmeng, sorry for the inconvenience - I've lost this PR due to a holiday, and now it has merge conflicts. 
Would you please take a look at those 🙏 ?

**Comment by kianmeng** [comment]
@lessless No worry. Please check again.

**Review by lessless — APPROVED** [review]

**Review by bharendt — APPROVED** [review]

**Comment by bharendt** [comment]
@kianmeng thank you, finally getting around to merging this!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Comment by kianmeng** [comment]
@mk Probably need to update to ExDoc 0.29 to get the latest features and layouts.

**Comment by bharendt** [comment]
@kianmeng thanks, updated: https://hexdocs.pm/edeliver/1.9.0-rc.2/readme.html

**Pull request merged**
