### PR TITLE
Sleep 1 before check node running

### PR DESCRIPTION
**Pull request by otaq**
boot time tolerance for low-spec machine

### CODE REVIEW

**Comment by otaq** [comment]
related issue https://elixirforum.com/t/edeliver-wont-start-project-at-production/2818

When release with distillery,  every time we execute node command, it reproduce `var/sys.config`. If edeliver check node running before node is completely booted, it will cause `configuration file must contain ONE list ended by <dot>` error. This happens on low tier machine(like single core CPU).

**Comment by kottkrig** [comment]
This seems to have solved my issues as well when running on a low-spec machine.

**Comment by samgranieri** [comment]
@boldpoker this also solved my issue when running on a low spec machine or virtualbox

**Comment by samgranieri** [comment]
@boldpoker can you merge this in?

**Comment by pedroassumpcao** [comment]
Can we have this merged in?

**Comment by samgranieri** [comment]
@bharendt merging in this issue would solve a lot of problems @pedroassumpcao and I are having at work. Can you merge this in?

**Comment by mk** [comment]
@samgranieri @pedroassumpcao Sorry we haven't been more responsive, we don't have much time to put into edeliver currently. Happy to add new maintainers here though if either of you would be interested.

**Comment by samgranieri** [comment]
@mk sure, i'll be happy to help.

**Comment by mk** [comment]
@samgranieri Great, thank you! I've sent you an invite.

**Pull request merged**
