### PR TITLE
Fix revision_from_version

### PR DESCRIPTION
**Pull request by belousovAV**
First metadata added by +
https://github.com/boldpoker/edeliver/blob/master/lib/mix/tasks/release_version.ex#L283

### CODE REVIEW

**Comment by bharendt** [comment]
Thanks, but I think that changes does not fix the problem completely. Before, appending and extracting the revision worked only if there were other metadata already appended to the version, e.g. the branch name like (`1.0.1+foobranch-98fa45`), but now it would only work if no other metadata are included into the version. It would be good if it would work for both cases, especially because the revision as onliest metadata does not give much information, e.g. which version is the more recent version etc.

**Comment by lessless** [comment]
Hi @belousovAV,

I will look further into it if you update it to not be a breaking change:

```
bash-3.2$ _version="1.2.0-ad70734"
bash-3.2$ echo  "${_version%%[-+]*}"
1.2.0
bash-3.2$ _version="1.2.0+ad70734"
bash-3.2$ echo  "${_version%%[-+]*}"
1.2.0
bash-3.2$
```

**Comment by lessless** [comment]
@bharendt @mk I know that you guys don't have much time, but in case there will be any can you please provide a test cases so I can evaluate the change?

Thanks

**Comment by bharendt** [comment]
Closing this as I'm clearing out stale branches. If anybody still wants this, please reopen.

**Pull request closed without merging**
