### PR TITLE
[WIP] Support for mix.releases for elixir >= 1.9

### LINKED ISSUE #322: Please update documentation with how to use edeliver with Mix releases. It only talks about distillery
Please update documentation with how to use edeliver with Mix releases. It only talks about distillery

### PR DESCRIPTION
**Pull request by dev-cyprium**
Closes #322 

**This is a heavy work in progress, and I'm mainly interested in feedback from the author and community in integrating mix-releases with edeliver**

I was really interested in trying out the new `mix releases` but they don't support any out-of-the box delivery mechanisms for shipping the actual build code for production.

## The Approach
So for now, I opted-in just for having a flag for using mix releases. Here's my example config:

```bash
# .deliver/config

APP="deliver_project"

# Instead of auto-detecting we  use the `mix-release` command as the release cmd
RELEASE_CMD="mix-release"

RELEASE_DIR="~/elixir_builds/_build/prod/rel/$APP"

BUILD_HOST="localhost"
BUILD_USER="deployer"
BUILD_AT="~/elixir_builds/"

STAGING_HOSTS="localhost"
STAGING_USER="deployer"
DELIVER_TO="~/elixir_web/"
```

### The Problems

1. The ping issue

One of the problems I've faced is to do with the `ping` command. Unfortunately `mix release` doesn't support the `ping` command out of the box. So the only viable option we have is to use something else, or to re-build the `ping` command as a module inside `edeliver` and use that to execute the `ping`. As I saw how complex the logic behind a simple ping is, I went for the second option which might be a bit hackish. Nonetheless, here's how I solved it:

```bash
__edeliver_node_running() {
      if [ \"$RELEASE_CMD\" = \"mix-release\" ]; then
        local __result=\"\$(bin/${APP} pid 2>&1)\"
        [[ \"\$__result\" =~ [0-9]+ ]]
      else
        bin/${APP} ping 2>/dev/null >/dev/null
      fi
    }
```

Basically, if we have a `pid` assigned using the pid command and if we do, then we know the node is in fact running.

2. start is not a daemon

For some reason, the mix team didn't make the `start` script a daemon. So, instead of doing `bin/appname start` you must do `bin/appname daemon` to get the process running.

Again, since `start` was hard-coded as a option in conjunction with `distillery` I had to add check if we're using `mix-release` and in that case not use the `start` command.

```bash
local _start_cmd=\"start\"
      if [ \"$RELEASE_CMD\" = \"mix-release\" ]; then
        _start_cmd=\"daemon\"
      fi
```

I've made a test project that uses this to demo a release. You can check it out: https://github.com/dev-cyprium/mix-release-edeliver

 ----

### Checklist 
- [x] Fix error when trying to run `mix edeliver` without `distilery`
- [x] Test if it's a non-breaking change
- [x] Deploy an example application with mix releases
- [ ] figure out a proper way of handling application "ping" to see if it's running
- [ ] make sure the `mix edeliver restart` command works
- [x] update documentation on custom modules, `vm.args`, `migrations`, etc.
- [x] add proper env flags to the command `mix release` inside the bash script

### CODE REVIEW

**Comment by tsloughter** [comment]
`start` is a bad name for the task because it gives the impression this is the recommended way to run the release, which these days it is not -- people tend to either be using something like systemd or a container, both of which should use `foreground` and not `start`/`daemon`. The use of `start` goes back to the rebar2 days and was something I regretted was kept in rebar3/relx. We've finally changed it to also be `daemon` in relx 4.0 and rebar3 3.14.0 (currently a release candidate).

**Comment by lessless** [comment]
Also rebar isn't really supported since 1.6 - there was a code cleanup. Maybe not throughout :)

**Comment by tsloughter** [comment]
Point was why did jose go with a different name for what distillery called `start`, I was just giving some background and what we discussed.

**Comment by lessless** [comment]
@tsloughter I didn't mean to interrupt - just wanted to highlight that there is no need to put extra effort in rebar compatability, even though it's still mentioned in the comments.

**Comment by dev-cyprium** [comment]
That's good to know, I wasn't aware rebar isn't compatible. I'll put some effort into changing the names to `foreground` and `daemon` as suggested. 👍

**Comment by tsloughter** [comment]
@dev-cyprium yes, it is used which is why mix release and rebar3 3.14 kept it, just under another name. This has had the useful result of people reevaluating and learning `daemon` is for unique cases (maybe embedded systems or another minimalist, and non-container, environment without an adequate init system) that the vast majority don't have and they should move to starting in the foreground

**Comment by bharendt** [comment]
@dev-cyprium I hope to revisit this in the future, but closing this for now since it's been a while.

**Pull request closed without merging**
